name: "Sender"
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Fixed cron syntax - was missing a *
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: send created sub
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: کانفیگ‌های بروز شده پروژه آنیتا
          document: configs.txt
