name: "Sender"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: send created sub
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: کانفیگ‌های پروژه آنیتا
          document: configs.txt
